// 監査ログの差分表示で「カラム名 → 日本語ラベル」を解決する。
// テーブル別にラベルを定義。未定義のカラムはカラム名をそのまま表示する。

const COMMON: Record<string, string> = {
  name: "名前",
  name_kana: "フリガナ",
  email: "メールアドレス",
  phone: "電話番号",
  fax: "FAX",
  postal_code: "郵便番号",
  address: "住所",
  notes: "メモ",
  internal_memo: "社内メモ",
  status: "ステータス",
  is_active: "有効",
  created_at: "作成日時",
  updated_at: "更新日時",
  deleted_at: "削除日時",
  company_id: "会社ID",
};

const TABLE_LABELS: Record<string, Record<string, string>> = {
  properties: {
    property_code: "物件コード",
    property_type: "物件種別",
    structure: "構造",
    floors: "階数",
    underground_floors: "地下階数",
    total_units: "総戸数",
    total_area_sqm: "延床面積",
    building_area_sqm: "建築面積",
    land_area_sqm: "土地面積",
    built_year: "築年",
    built_month: "築月",
    renovation_year: "改装年",
    renovation_month: "改装月",
    nearest_station: "最寄り駅",
    walk_minutes: "徒歩(分)",
    management_form: "管理形態",
    management_company: "管理会社",
    management_fee_type: "管理手数料種別",
    management_fee_rate: "管理手数料率",
    management_fee_amount: "管理手数料額",
    parking: "駐車場",
    parking_fee: "駐車場料金",
    owner_id: "オーナーID",
    approver_user_id: "承認者",
    appeal_points: "アピールポイント",
    estate_license: "宅建業免許",
  },
  units: {
    unit_number: "部屋番号",
    floor: "階",
    layout: "間取り",
    area_sqm: "面積",
    rent: "賃料",
    management_fee: "管理費",
    deposit: "敷金",
    key_money: "礼金",
    property_id: "物件ID",
    damage_notes: "損耗メモ",
  },
  tenants: {
    date_of_birth: "生年月日",
    gender: "性別",
    nationality: "国籍",
    workplace: "勤務先",
    workplace_phone: "勤務先電話",
    annual_income: "年収(万円)",
    emergency_contact_name: "緊急連絡先 氏名",
    emergency_contact_phone: "緊急連絡先 電話",
    emergency_contact_relation: "緊急連絡先 続柄",
    guarantee_type: "保証区分",
    guarantee_company_name: "保証会社名",
    guarantee_contract_number: "保証契約番号",
    guarantee_fee: "保証料",
    guarantor_name: "連帯保証人 氏名",
    guarantor_phone: "連帯保証人 電話",
    guarantor_address: "連帯保証人 住所",
    guarantor_annual_income: "連帯保証人 年収",
    guarantor_relation: "連帯保証人 続柄",
  },
  contracts: {
    unit_id: "部屋ID",
    tenant_id: "入居者ID",
    contract_type: "契約種別",
    start_date: "契約開始日",
    end_date: "契約終了日",
    rent: "賃料",
    management_fee: "管理費",
    move_in_date: "入居日",
    move_out_date: "退去日",
    deposit: "敷金",
    key_money: "礼金",
    renewal_fee: "更新料",
  },
  rent_billings: {
    contract_id: "契約ID",
    billing_month: "請求月",
    rent: "賃料",
    management_fee: "管理費",
    other_amount: "その他金額",
    other_description: "その他内容",
    total_amount: "合計金額",
    due_date: "支払期限",
  },
  rent_payments: {
    billing_id: "請求ID",
    amount: "金額",
    payment_method: "支払方法",
    payment_date: "入金日",
  },
  cases: {
    title: "件名",
    description: "詳細",
    category: "カテゴリ",
    priority: "優先度",
    property_id: "物件ID",
    unit_id: "部屋ID",
    tenant_id: "入居者ID",
    reported_date: "受付日",
    completed_date: "完了日",
    vendor_name: "業者名",
    estimated_cost: "見積金額",
    actual_cost: "実費",
    source: "発生元",
  },
  expenses: {
    expense_date: "経費発生日",
    amount: "金額",
    category: "カテゴリ",
    description: "内容",
    payee_id: "支払先ID",
    property_id: "物件ID",
    owner_id: "オーナーID",
    case_id: "対応案件ID",
    contract_id: "契約ID",
    allocation_method: "按分方法",
    submitted_at: "申請日時",
    approved_at: "承認日時",
    rejected_at: "却下日時",
    approver_user_id: "承認者",
    reject_reason: "却下理由",
  },
  owners: {
    bank_name: "銀行名",
    bank_code: "銀行コード",
    bank_branch: "支店名",
    bank_branch_code: "支店コード",
    bank_account_type: "口座種別",
    bank_account_number: "口座番号",
    bank_account_holder: "口座名義",
    bank_account_holder_kana: "口座名義カナ",
  },
  owner_remittances: {
    owner_id: "オーナーID",
    remittance_month: "送金対象月",
    total_rent: "家賃収入",
    management_fee_deducted: "管理手数料控除",
    expense_deducted: "経費控除",
    net_amount: "送金額",
    payment_method: "支払方法",
    sent_date: "送金日",
    manual_override: "手動上書き",
    manual_net_amount: "手動送金額",
  },
  payees: {
    category: "カテゴリ",
    bank_name: "銀行名",
    bank_code: "銀行コード",
    branch_name: "支店名",
    branch_code: "支店コード",
    account_type: "口座種別",
    account_number: "口座番号",
    account_holder_kana: "口座名義カナ",
  },
};

export function fieldLabel(table: string, column: string): string {
  return TABLE_LABELS[table]?.[column] ?? COMMON[column] ?? column;
}

// 差分表示で無視するカラム（毎回変わるか、機械的で見せても意味がないもの）
const IGNORE = new Set([
  "id", "company_id", "created_at", "updated_at",
]);

export function isIgnoredField(column: string): boolean {
  return IGNORE.has(column);
}
